allowBuilds:
  '@sentry/cli': true
  '@swc/core': true
  core-js: true
  esbuild: true

overrides:
  serialize-javascript: 7.1.2
  dompurify: 3.4.16
  "uuid@<11.1.1": 11.1.1
  "source-map-js@<1.2.2": 1.2.2
  "postcss-selector-parser@<7.1.6": 7.1.6

patchedDependencies:
  braces@3.0.3: patches/braces@3.0.3.patch
